// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/demo.proto

package org.abondar.experimental.protobufdemo.model;

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.PersonMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string firstName = 1;</code>
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 2;</code>
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.model.PersonMsg.Employee emp = 5;</code>
     */
    int getEmpValue();
    /**
     * <code>.model.PersonMsg.Employee emp = 5;</code>
     */
    org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee getEmp();

    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    boolean hasDepartment();
    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDepartment();
    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder getDepartmentOrBuilder();
  }
  /**
   * Protobuf type {@code model.PersonMsg}
   */
  public  static final class PersonMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.PersonMsg)
      PersonMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonMsg.newBuilder() to construct.
    private PersonMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonMsg() {
      firstName_ = "";
      lastName_ = "";
      id_ = 0;
      email_ = "";
      emp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              emp_ = rawValue;
              break;
            }
            case 50: {
              org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder subBuilder = null;
              if (department_ != null) {
                subBuilder = department_.toBuilder();
              }
              department_ = input.readMessage(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(department_);
                department_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.abondar.experimental.protobufdemo.model.Person.PersonMsg.class, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code model.PersonMsg.Employee}
     */
    public enum Employee
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEVELOPER = 0;</code>
       */
      DEVELOPER(0),
      /**
       * <code>QA = 1;</code>
       */
      QA(1),
      /**
       * <code>MANAGER = 2;</code>
       */
      MANAGER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEVELOPER = 0;</code>
       */
      public static final int DEVELOPER_VALUE = 0;
      /**
       * <code>QA = 1;</code>
       */
      public static final int QA_VALUE = 1;
      /**
       * <code>MANAGER = 2;</code>
       */
      public static final int MANAGER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Employee valueOf(int value) {
        return forNumber(value);
      }

      public static Employee forNumber(int value) {
        switch (value) {
          case 0: return DEVELOPER;
          case 1: return QA;
          case 2: return MANAGER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Employee>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Employee> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Employee>() {
              public Employee findValueByNumber(int number) {
                return Employee.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.abondar.experimental.protobufdemo.model.Person.PersonMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Employee[] VALUES = values();

      public static Employee valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Employee(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:model.PersonMsg.Employee)
    }

    public interface DepartmentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:model.PersonMsg.Department)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string departmentName = 1;</code>
       */
      java.lang.String getDepartmentName();
      /**
       * <code>string departmentName = 1;</code>
       */
      com.google.protobuf.ByteString
          getDepartmentNameBytes();
    }
    /**
     * Protobuf type {@code model.PersonMsg.Department}
     */
    public  static final class Department extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:model.PersonMsg.Department)
        DepartmentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Department.newBuilder() to construct.
      private Department(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Department() {
        departmentName_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Department(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                departmentName_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_Department_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_Department_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.class, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder.class);
      }

      public static final int DEPARTMENTNAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object departmentName_;
      /**
       * <code>string departmentName = 1;</code>
       */
      public java.lang.String getDepartmentName() {
        java.lang.Object ref = departmentName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          departmentName_ = s;
          return s;
        }
      }
      /**
       * <code>string departmentName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDepartmentNameBytes() {
        java.lang.Object ref = departmentName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          departmentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getDepartmentNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, departmentName_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDepartmentNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, departmentName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department)) {
          return super.equals(obj);
        }
        org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department other = (org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department) obj;

        boolean result = true;
        result = result && getDepartmentName()
            .equals(other.getDepartmentName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DEPARTMENTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDepartmentName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code model.PersonMsg.Department}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:model.PersonMsg.Department)
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_Department_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_Department_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.class, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder.class);
        }

        // Construct using org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          departmentName_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_Department_descriptor;
        }

        @java.lang.Override
        public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDefaultInstanceForType() {
          return org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.getDefaultInstance();
        }

        @java.lang.Override
        public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department build() {
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department buildPartial() {
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department result = new org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department(this);
          result.departmentName_ = departmentName_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department) {
            return mergeFrom((org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department other) {
          if (other == org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.getDefaultInstance()) return this;
          if (!other.getDepartmentName().isEmpty()) {
            departmentName_ = other.departmentName_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object departmentName_ = "";
        /**
         * <code>string departmentName = 1;</code>
         */
        public java.lang.String getDepartmentName() {
          java.lang.Object ref = departmentName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            departmentName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string departmentName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDepartmentNameBytes() {
          java.lang.Object ref = departmentName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            departmentName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string departmentName = 1;</code>
         */
        public Builder setDepartmentName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          departmentName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string departmentName = 1;</code>
         */
        public Builder clearDepartmentName() {
          
          departmentName_ = getDefaultInstance().getDepartmentName();
          onChanged();
          return this;
        }
        /**
         * <code>string departmentName = 1;</code>
         */
        public Builder setDepartmentNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          departmentName_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:model.PersonMsg.Department)
      }

      // @@protoc_insertion_point(class_scope:model.PersonMsg.Department)
      private static final org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department();
      }

      public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Department>
          PARSER = new com.google.protobuf.AbstractParser<Department>() {
        @java.lang.Override
        public Department parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Department(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Department> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Department> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 1;</code>
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 2;</code>
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMP_FIELD_NUMBER = 5;
    private int emp_;
    /**
     * <code>.model.PersonMsg.Employee emp = 5;</code>
     */
    public int getEmpValue() {
      return emp_;
    }
    /**
     * <code>.model.PersonMsg.Employee emp = 5;</code>
     */
    public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee getEmp() {
      @SuppressWarnings("deprecation")
      org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee result = org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.valueOf(emp_);
      return result == null ? org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.UNRECOGNIZED : result;
    }

    public static final int DEPARTMENT_FIELD_NUMBER = 6;
    private org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department department_;
    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    public boolean hasDepartment() {
      return department_ != null;
    }
    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDepartment() {
      return department_ == null ? org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.getDefaultInstance() : department_;
    }
    /**
     * <code>.model.PersonMsg.Department department = 6;</code>
     */
    public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder getDepartmentOrBuilder() {
      return getDepartment();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastName_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (emp_ != org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.DEVELOPER.getNumber()) {
        output.writeEnum(5, emp_);
      }
      if (department_ != null) {
        output.writeMessage(6, getDepartment());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastName_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (emp_ != org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.DEVELOPER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, emp_);
      }
      if (department_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDepartment());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.abondar.experimental.protobufdemo.model.Person.PersonMsg)) {
        return super.equals(obj);
      }
      org.abondar.experimental.protobufdemo.model.Person.PersonMsg other = (org.abondar.experimental.protobufdemo.model.Person.PersonMsg) obj;

      boolean result = true;
      result = result && getFirstName()
          .equals(other.getFirstName());
      result = result && getLastName()
          .equals(other.getLastName());
      result = result && (getId()
          == other.getId());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && emp_ == other.emp_;
      result = result && (hasDepartment() == other.hasDepartment());
      if (hasDepartment()) {
        result = result && getDepartment()
            .equals(other.getDepartment());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + EMP_FIELD_NUMBER;
      hash = (53 * hash) + emp_;
      if (hasDepartment()) {
        hash = (37 * hash) + DEPARTMENT_FIELD_NUMBER;
        hash = (53 * hash) + getDepartment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.abondar.experimental.protobufdemo.model.Person.PersonMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.PersonMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.PersonMsg)
        org.abondar.experimental.protobufdemo.model.Person.PersonMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.abondar.experimental.protobufdemo.model.Person.PersonMsg.class, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Builder.class);
      }

      // Construct using org.abondar.experimental.protobufdemo.model.Person.PersonMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        firstName_ = "";

        lastName_ = "";

        id_ = 0;

        email_ = "";

        emp_ = 0;

        if (departmentBuilder_ == null) {
          department_ = null;
        } else {
          department_ = null;
          departmentBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.abondar.experimental.protobufdemo.model.Person.internal_static_model_PersonMsg_descriptor;
      }

      @java.lang.Override
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg getDefaultInstanceForType() {
        return org.abondar.experimental.protobufdemo.model.Person.PersonMsg.getDefaultInstance();
      }

      @java.lang.Override
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg build() {
        org.abondar.experimental.protobufdemo.model.Person.PersonMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg buildPartial() {
        org.abondar.experimental.protobufdemo.model.Person.PersonMsg result = new org.abondar.experimental.protobufdemo.model.Person.PersonMsg(this);
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        result.id_ = id_;
        result.email_ = email_;
        result.emp_ = emp_;
        if (departmentBuilder_ == null) {
          result.department_ = department_;
        } else {
          result.department_ = departmentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.abondar.experimental.protobufdemo.model.Person.PersonMsg) {
          return mergeFrom((org.abondar.experimental.protobufdemo.model.Person.PersonMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.abondar.experimental.protobufdemo.model.Person.PersonMsg other) {
        if (other == org.abondar.experimental.protobufdemo.model.Person.PersonMsg.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.emp_ != 0) {
          setEmpValue(other.getEmpValue());
        }
        if (other.hasDepartment()) {
          mergeDepartment(other.getDepartment());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.abondar.experimental.protobufdemo.model.Person.PersonMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.abondar.experimental.protobufdemo.model.Person.PersonMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 1;</code>
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 1;</code>
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 2;</code>
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 2;</code>
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int emp_ = 0;
      /**
       * <code>.model.PersonMsg.Employee emp = 5;</code>
       */
      public int getEmpValue() {
        return emp_;
      }
      /**
       * <code>.model.PersonMsg.Employee emp = 5;</code>
       */
      public Builder setEmpValue(int value) {
        emp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.model.PersonMsg.Employee emp = 5;</code>
       */
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee getEmp() {
        @SuppressWarnings("deprecation")
        org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee result = org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.valueOf(emp_);
        return result == null ? org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee.UNRECOGNIZED : result;
      }
      /**
       * <code>.model.PersonMsg.Employee emp = 5;</code>
       */
      public Builder setEmp(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Employee value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        emp_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.model.PersonMsg.Employee emp = 5;</code>
       */
      public Builder clearEmp() {
        
        emp_ = 0;
        onChanged();
        return this;
      }

      private org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department department_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder> departmentBuilder_;
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public boolean hasDepartment() {
        return departmentBuilder_ != null || department_ != null;
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department getDepartment() {
        if (departmentBuilder_ == null) {
          return department_ == null ? org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.getDefaultInstance() : department_;
        } else {
          return departmentBuilder_.getMessage();
        }
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public Builder setDepartment(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department value) {
        if (departmentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          department_ = value;
          onChanged();
        } else {
          departmentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public Builder setDepartment(
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder builderForValue) {
        if (departmentBuilder_ == null) {
          department_ = builderForValue.build();
          onChanged();
        } else {
          departmentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public Builder mergeDepartment(org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department value) {
        if (departmentBuilder_ == null) {
          if (department_ != null) {
            department_ =
              org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.newBuilder(department_).mergeFrom(value).buildPartial();
          } else {
            department_ = value;
          }
          onChanged();
        } else {
          departmentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public Builder clearDepartment() {
        if (departmentBuilder_ == null) {
          department_ = null;
          onChanged();
        } else {
          department_ = null;
          departmentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder getDepartmentBuilder() {
        
        onChanged();
        return getDepartmentFieldBuilder().getBuilder();
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      public org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder getDepartmentOrBuilder() {
        if (departmentBuilder_ != null) {
          return departmentBuilder_.getMessageOrBuilder();
        } else {
          return department_ == null ?
              org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.getDefaultInstance() : department_;
        }
      }
      /**
       * <code>.model.PersonMsg.Department department = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder> 
          getDepartmentFieldBuilder() {
        if (departmentBuilder_ == null) {
          departmentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.Department.Builder, org.abondar.experimental.protobufdemo.model.Person.PersonMsg.DepartmentOrBuilder>(
                  getDepartment(),
                  getParentForChildren(),
                  isClean());
          department_ = null;
        }
        return departmentBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.PersonMsg)
    }

    // @@protoc_insertion_point(class_scope:model.PersonMsg)
    private static final org.abondar.experimental.protobufdemo.model.Person.PersonMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.abondar.experimental.protobufdemo.model.Person.PersonMsg();
    }

    public static org.abondar.experimental.protobufdemo.model.Person.PersonMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonMsg>
        PARSER = new com.google.protobuf.AbstractParser<PersonMsg>() {
      @java.lang.Override
      public PersonMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.abondar.experimental.protobufdemo.model.Person.PersonMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PersonMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_PersonMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_PersonMsg_Department_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_PersonMsg_Department_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/resources/demo.proto\022\005model\"\372" +
      "\001\n\tPersonMsg\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastN" +
      "ame\030\002 \001(\t\022\n\n\002id\030\003 \001(\005\022\r\n\005email\030\004 \001(\t\022&\n\003" +
      "emp\030\005 \001(\0162\031.model.PersonMsg.Employee\022/\n\n" +
      "department\030\006 \001(\0132\033.model.PersonMsg.Depar" +
      "tment\032$\n\nDepartment\022\026\n\016departmentName\030\001 " +
      "\001(\t\".\n\010Employee\022\r\n\tDEVELOPER\020\000\022\006\n\002QA\020\001\022\013" +
      "\n\007MANAGER\020\002B5\n+org.abondar.experimental." +
      "protobufdemo.modelB\006Personb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_PersonMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_PersonMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_PersonMsg_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Id", "Email", "Emp", "Department", });
    internal_static_model_PersonMsg_Department_descriptor =
      internal_static_model_PersonMsg_descriptor.getNestedTypes().get(0);
    internal_static_model_PersonMsg_Department_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_PersonMsg_Department_descriptor,
        new java.lang.String[] { "DepartmentName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
